server:
  port: 8089

# 应用配置
app:
  config:
    api-version: v1
    # 跨域，开发阶段可以配置为 * 不限制
    cross-origin: '*'
    # 访问频次限制
    limit-count: 10
    # 白名单，不做频次拦截【微信的openai】oxfA9w8-23yvwTmo2ombz0E4zJv4
    white-list: ojbZUv18lbmriaTjcCWBYkOrSbHA
    # 访问频率限制
    access-frequency: 3

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy
# ChatGLM SDK Config
chatglm:
  sdk:
    config:
      # 官网地址
      api-host: https://open.bigmodel.cn/
      # 官网申请 https://open.bigmodel.cn/usercenter/apikeys - 自己可申请
      api-secret-key: 2f35c38c217c30ad13e87d83de59aa22.UUjqNdr0pJFpDtJn

# wx 公众号配置
wx:
  config:
    originalid: xxxxxxxx
    appid: xxxxxxxx
    token: mywx
